/**
 * tests/fixtures/phase2/ — Phase 2 test fixtures
 *
 * Covers entity resolution (merge/split/alias) and reliability layers.
 */

export const BASE_BATCH = {
  schema_version: 1,
  imported_at: '2026-03-21T00:00:00.000Z',
  records: [
    {
      hadith_id: 'hadith-001',
      family_id: 'family-001',
      source_ref: {
        collection: 'Test Collection',
        source_type: 'print',
        source_locator: 'p.1',
        ingested_at: '2026-03-21T00:00:00.000Z',
      },
      variants: [{
        variant_id: 'v1',
        isnad_chain: ['narrator-a', 'narrator-b', 'narrator-c'],
      }],
      reliability_evidence: [],
    },
  ],
  narrators: [
    {
      narrator_id: 'narrator-a',
      names: ['Narrator A', 'Abu A'],
      aliases: [],
      tags: [],
      reliability_evidence: [],
    },
    {
      narrator_id: 'narrator-b',
      names: ['Narrator B'],
      aliases: [],
      tags: [],
      reliability_evidence: [],
    },
    {
      narrator_id: 'narrator-c',
      names: ['Narrator C'],
      aliases: [],
      tags: [],
      reliability_evidence: [],
    },
  ],
};

export const EVIDENCE_THIQ = {
  evidence_id: 'ev-t001',
  narrator_id: 'narrator-a',
  rating: 'thiqah',
  rating_confidence: 0.9,
  scholar: 'Ibn Hajar',
  work: 'Taqrib',
  source_type: 'print',
  source_ref: {
    collection: 'Taqrib al-Tahdhib',
    source_type: 'print',
    source_locator: 'p. 100',
    ingested_at: '2026-03-21T00:00:00.000Z',
  },
  ingested_at: '2026-03-21T00:00:00.000Z',
};

export const EVIDENCE_DAIF = {
  evidence_id: 'ev-d001',
  narrator_id: 'narrator-a',
  rating: 'daif',
  rating_confidence: 0.7,
  scholar: 'Dhahabi',
  work: 'Mizan',
  source_type: 'print',
  source_ref: {
    collection: 'Mizan al-I\'tidal',
    source_type: 'print',
    source_locator: 'p. 50',
    ingested_at: '2026-03-21T00:00:00.000Z',
  },
  ingested_at: '2026-03-21T00:00:00.000Z',
};

export const EVIDENCE_ANALYTICAL = {
  evidence_id: 'ev-cl001',
  narrator_id: 'narrator-b',
  rating: 'thiqah',
  rating_confidence: 0.6,
  scholar: 'CL Analysis',
  work: 'Structural Analysis v1',
  source_type: 'print',
  source_ref: {
    collection: 'CL Candidate Report',
    source_type: 'print',
    source_locator: 'Generated by Phase 3',
    ingested_at: '2026-03-21T00:00:00.000Z',
  },
  ingested_at: '2026-03-21T00:00:00.000Z',
};

export const EVIDENCE_NO_PROVENANCE = {
  evidence_id: 'ev-bad',
  narrator_id: 'narrator-c',
  rating: 'thiqah',
  source_ref: {}, // missing required fields
  ingested_at: '2026-03-21T00:00:00.000Z',
};

export const BATCH_WITH_AMBIGUOUS_NAMES = {
  schema_version: 1,
  imported_at: '2026-03-21T00:00:00.000Z',
  records: [
    {
      hadith_id: 'h1',
      family_id: 'f1',
      source_ref: {
        collection: 'X', source_type: 'print', source_locator: 'p1', ingested_at: '2026-03-21T00:00:00.000Z',
      },
      variants: [{ variant_id: 'v1', isnad_chain: ['hisham-1', 'hisham-2', 'urwah'] }],
    },
  ],
  narrators: [
    { narrator_id: 'hisham-1', names: ['Hisham ibn Urwah'], aliases: ['Hisham al-Madani'], tags: [], reliability_evidence: [] },
    { narrator_id: 'hisham-2', names: ['Hisham al-Madani', 'Hisham ibn Urwah'], aliases: [], tags: [], reliability_evidence: [] },
    { narrator_id: 'urwah', names: ['Urwah ibn al-Zubayr'], aliases: [], tags: [], reliability_evidence: [] },
  ],
};

export const BATCH_PRE_MERGE = {
  schema_version: 1,
  imported_at: '2026-03-21T00:00:00.000Z',
  records: [
    {
      hadith_id: 'h1',
      family_id: 'f1',
      source_ref: {
        collection: 'X', source_type: 'print', source_locator: 'p1', ingested_at: '2026-03-21T00:00:00.000Z',
      },
      variants: [{ variant_id: 'v1', isnad_chain: ['narr-x', 'narr-y', 'narr-z'] }],
      reliability_evidence: [
        {
          evidence_id: 'ev-x',
          narrator_id: 'narr-x',
          rating: 'thiqah',
          source_type: 'print',
          source_ref: { collection: 'Tahdhib', source_type: 'print', source_locator: 'p1', ingested_at: '2026-03-21T00:00:00.000Z' },
          ingested_at: '2026-03-21T00:00:00.000Z',
        },
      ],
    },
  ],
  narrators: [
    { narrator_id: 'narr-x', names: ['Narr X'], tags: [], reliability_evidence: [] },
    { narrator_id: 'narr-y', names: ['Narr Y'], tags: [], reliability_evidence: [] },
    { narrator_id: 'narr-z', names: ['Narr Z'], tags: [], reliability_evidence: [] },
  ],
};
